### ISSUE TITLE
Snapshots without destination broken since 0.6.4

### ISSUE THREAD

**Issue by silkeh** [masc3d/btrfs-sxbackup#30]
It seems release 0.6.4 made some changes that break the creation of snapshots without a destination:

```
$ btrfs-sxbackup -v run /mnt
INFO btrfs-sxbackup v0.6.6
DEBUG ['bash', '-c', 'if [ -f "/mnt/.btrfs-sxbackup" ]; then exit 10; fi']
DEBUG ['bash', '-c', 'cat "/mnt/.sxbackup/.btrfs-sxbackup"']
INFO source :: url [/mnt/] container [.sxbackup/] retention [1d:4/d, 1w:2/w, 3m:2/m, 12m:none] compress [False]
INFO preparing environment
DEBUG ['bash', '-c', 'if [ ! -d "/mnt/.sxbackup/" ]; then btrfs sub create "/mnt/.sxbackup/"; fi']
DEBUG ['bash', '-c', 'btrfs sub show "/mnt/.sxbackup/"']
DEBUG ['bash', '-c', 'if [ -d "/mnt/.sxbackup/.temp"* ]; then btrfs sub del "/mnt/.sxbackup/.temp"*; fi']
INFO source :: retrieving snapshots
DEBUG ['bash', '-c', 'btrfs sub list -o "/mnt/.sxbackup/"']
ERROR 'NoneType' object has no attribute 'snapshots'
ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/btrfs_sxbackup/__main__.py", line 216, in main
    job.run()
  File "/usr/local/lib/python3.4/dist-packages/btrfs_sxbackup/core.py", line 963, in run
    if self.source.snapshots[0].name.timestamp == self.destination.snapshots[0].name.timestamp:
AttributeError: 'NoneType' object has no attribute 'snapshots'
```

**Comment by masc3d** [comment]
indeed. thanks for reporting
