### ISSUE TITLE
btrfs send returned non-zero exit status -9 with latest HEAD

### ISSUE THREAD

**Issue by dev-zero** [masc3d/btrfs-sxbackup#7]
It seems to call `btrfs send` again after having deleted the temporary snapshot:

```
~ # btrfs-sxbackup -vvv run /var/backup/myhost.root
INFO btrfs-sxbackup v0.5.5
DEBUG ['bash', '-c', 'if [ -f "/var/backup/myhost.root/.btrfs-sxbackup" ] ; then exit 10; fi']
DEBUG ['bash', '-c', 'cat "/var/backup/myhost.root/.btrfs-sxbackup"']
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'cat "/.sxbackup/.btrfs-sxbackup"']
INFO source :: url [ssh://root@myhost.localdomain:/] container [/.sxbackup/] retention [10] compress [False]
INFO destination :: url [/var/backup/myhost.root/] retention [10] compress [True]
INFO preparing environment
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'if [ ! -d "/.sxbackup/" ] ; then btrfs sub create "/.sxbackup/"; fi']
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'btrfs sub show "/.sxbackup/"']
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'if [ -d "/.sxbackup/.temp"* ]; then btrfs sub del "/.sxbackup/.temp"*; fi']
DEBUG ['bash', '-c', 'if [ ! -d "/var/backup/myhost.root/" ] ; then btrfs sub create "/var/backup/myhost.root/"; fi']
DEBUG ['bash', '-c', 'btrfs sub show "/var/backup/myhost.root/"']
DEBUG ['bash', '-c', 'if [ -d "/var/backup/myhost.root/.temp"* ]; then btrfs sub del "/var/backup/myhost.root/.temp"*; fi']
INFO source :: retrieving snapshot names
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'btrfs sub list -o "/.sxbackup/"']
INFO destination :: retrieving snapshot names
DEBUG ['bash', '-c', 'btrfs sub list -o "/var/backup/myhost.root/"']
INFO source :: creating snapshot
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'btrfs sub snap -r "/" "/.sxbackup/.temp.2df46184af934699946224a049785f5c" && sync']
DEBUG ['bash', '-c', 'if [ -d "/var/backup/myhost.root/.temp.2df46184af934699946224a049785f5c" ]; then exit 10; fi']
INFO source :: transferring snapshot
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'btrfs send -p "/.sxbackup/sx-20150323-142542-utc" "/.sxbackup/.temp.2df46184af934699946224a049785f5c"']
DEBUG ['bash', '-c', 'type pv']
DEBUG ['bash', '-c', 'btrfs receive "/var/backup/myhost.root/"']
INFO destination :: removing subvolume [/var/backup/myhost.root/.temp.2df46184af934699946224a049785f5c]
DEBUG ['bash', '-c', 'if [ -d "/var/backup/myhost.root/.temp.2df46184af934699946224a049785f5c" ]; then btrfs sub del "/var/backup/myhost.root/.temp.2df46184af934699946224a049785f5c"; fi']
INFO source :: removing subvolume [/.sxbackup/.temp.2df46184af934699946224a049785f5c]
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'if [ -d "/.sxbackup/.temp.2df46184af934699946224a049785f5c" ]; then btrfs sub del "/.sxbackup/.temp.2df46184af934699946224a049785f5c"; fi']
ERROR Command '['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'btrfs send -p "/.sxbackup/sx-20150323-142542-utc" "/.sxbackup/.temp.2df46184af934699946224a049785f5c"']' returned non-zero exit status -9
ERROR At subvol /.sxbackup/.temp.2df46184af934699946224a049785f5c
ERROR Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/btrfs_sxbackup/__main__.py", line 192, in <module>
    job.run()
  File "/usr/lib64/python3.3/site-packages/btrfs_sxbackup/core.py", line 904, in run
    raise e
  File "/usr/lib64/python3.3/site-packages/btrfs_sxbackup/core.py", line 900, in run
    compress=self.source.compress)
  File "/usr/lib64/python3.3/site-packages/btrfs_sxbackup/core.py", line 294, in transfer_btrfs_snapshot
    raise e
  File "/usr/lib64/python3.3/site-packages/btrfs_sxbackup/core.py", line 282, in transfer_btrfs_snapshot
    send_process.stderr.read())
subprocess.CalledProcessError: Command '['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'root@myhost.localdomain', 'btrfs send -p "/.sxbackup/sx-20150323-142542-utc" "/.sxbackup/.temp.2df46184af934699946224a049785f5c"']' returned non-zero exit status -9

61.2KiB 0:00:02 [22.8KiB/s] [   <=>                                                                                       ]
```

The configuration reads as follows (same behaviour with a fresh configuration):
```
[Destination]
source = ssh://root@myhost.localdomain:/
source-container = /.sxbackup
keep = 10
compress = True
```

**Comment by masc3d** [comment]
it's not invoking send twice, that's just the error output for the command. can you please post btrfs-sxbackup info for this job and also kernel and btrfs-progs versions for source and destination?

**Comment by dev-zero** [comment]
```
~ # btrfs-sxbackup info /var/backup/myhost.root
INFO btrfs-sxbackup v0.5.5
INFO source :: retrieving snapshot names
INFO destination :: retrieving snapshot names
   Compress               False
   Source URL             ssh://root@myhost.localdomain:
   Source container       /.sxbackup
   Source retention       10
   Source snapshots       sx-20150323-142542-utc
                          sx-20150203-082911-utc
                          sx-20150201-100748-utc
   Destination URL        /var/backup/myhost.root
   Destination retention  10
   Destination snapshots  sx-20150323-142542-utc
                          sx-20150203-082911-utc
                          sx-20150201-100748-utc
```

* source kernel: 3.17.3-hardened
* destination kernel: 3.18.2-hardened-r1
* source btrfs-progs: v3.18.2
* destination btrfs-progs: v3.18.2

**Comment by masc3d** [comment]
info looks ok, but this seems to relate to btrfs send/receive rather than btrfs-sxbackup. have there been any changes in kernel/btrfs-progs since March 23? I have seen odd things with btrfs send/receive occasionally when kernel versions differ.

**Comment by dev-zero** [comment]
No, kernel on dest was last updated on Jan 18, the source host is running since 139 days and btrfs-progs was updated on both machines on January 31.

*argh* sorry, my bad. I was again using the destination mounted with `subvol=backup` instead of the root-mounted filesystem. When using the root-mounted volume it works.
My apologies.
