### ISSUE TITLE
File contains no section headers

### ISSUE THREAD

**Issue by dkragen** [masc3d/btrfs-sxbackup#77]
Initialization proceeds fine, but when I try to run a backup I get the following error:

ERROR File contains no section headers.
file: '<???>', line: 16
'\x1b[39m\x1b[49m\x1b[0m'

Do you have any ideas what is going on?

**Comment by masc3d** [comment]
do you have stacktrace?

**Comment by dkragen** [comment]
Sorry, I don't. I gave up on this and switched to a different btrfs
backup solution.

**Comment by bhelm** [comment]
I encountered that issue when the remote location responded with a warning. after fixing it, everything worked.

```
DEBUG ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', '192.168.2.4', 'cat "/.sxbackup/.btrfs-sxbackup"']
['bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)', '[Source]', 'uuid = 37364c59-01d3-4961-9f3e-e2d27069176b', 'retention = 3', '']
ERROR File contains no section headers.
file: '<???>', line: 1
'bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)'
ERROR Traceback (most recent call last):
  File "/root/venv/lib/python3.11/site-packages/btrfs_sxbackup/__main__.py", line 215, in main
    job = Job.load(urllib.parse.urlsplit(subvolume))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/btrfs_sxbackup/core.py", line 869, in load
    corresponding_location.read_configuration()
  File "/root/venv/lib/python3.11/site-packages/btrfs_sxbackup/core.py", line 678, in read_configuration
    parser.read_file(file)
  File "/usr/lib/python3.11/configparser.py", line 734, in read_file
    self._read(f, source)
  File "/usr/lib/python3.11/configparser.py", line 1101, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<???>', line: 1
```

```
# ssh 192.168.2.4 cat "/.sxbackup/.btrfs-sxbackup"
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[Source]
uuid = 37364c59-01d3-4961-9f3e-e2d27069176b
retention = 3
```

just in case someone comes along.
